// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AspNetRouteMetricsSnapshotModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The capturedAtUtc property</summary>
        public DateTimeOffset? CapturedAtUtc { get; set; }
        /// <summary>The processStartedAtUtc property</summary>
        public DateTimeOffset? ProcessStartedAtUtc { get; set; }
        /// <summary>The routes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.AspNetRouteMetricsModel>? Routes { get; set; }
#nullable restore
#else
        public List<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.AspNetRouteMetricsModel> Routes { get; set; }
#endif
        /// <summary>The trackedRouteCount property</summary>
        public long? TrackedRouteCount { get; set; }
        /// <summary>The uptimeSeconds property</summary>
        public double? UptimeSeconds { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.AspNetRouteMetricsSnapshotModel"/> and sets the default values.
        /// </summary>
        public AspNetRouteMetricsSnapshotModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.AspNetRouteMetricsSnapshotModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.AspNetRouteMetricsSnapshotModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.AspNetRouteMetricsSnapshotModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "capturedAtUtc", n => { CapturedAtUtc = n.GetDateTimeOffsetValue(); } },
                { "processStartedAtUtc", n => { ProcessStartedAtUtc = n.GetDateTimeOffsetValue(); } },
                { "routes", n => { Routes = n.GetCollectionOfObjectValues<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.AspNetRouteMetricsModel>(global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.AspNetRouteMetricsModel.CreateFromDiscriminatorValue)?.AsList(); } },
                { "trackedRouteCount", n => { TrackedRouteCount = n.GetLongValue(); } },
                { "uptimeSeconds", n => { UptimeSeconds = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("capturedAtUtc", CapturedAtUtc);
            writer.WriteDateTimeOffsetValue("processStartedAtUtc", ProcessStartedAtUtc);
            writer.WriteCollectionOfObjectValues<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.AspNetRouteMetricsModel>("routes", Routes);
            writer.WriteLongValue("trackedRouteCount", TrackedRouteCount);
            writer.WriteDoubleValue("uptimeSeconds", UptimeSeconds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
