// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BrokerMessageHandlerStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "Processing")]
        #pragma warning disable CS1591
        Processing,
        #pragma warning restore CS1591
        [EnumMember(Value = "Succeeded")]
        #pragma warning disable CS1591
        Succeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "Failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeadLettered")]
        #pragma warning disable CS1591
        DeadLettered,
        #pragma warning restore CS1591
        [EnumMember(Value = "Expired")]
        #pragma warning disable CS1591
        Expired,
        #pragma warning restore CS1591
    }
}
