// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BrokerMessageHandlerInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attemptCount property</summary>
        public int? AttemptCount { get; set; }
        /// <summary>The handlerType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HandlerType { get; set; }
#nullable restore
#else
        public string HandlerType { get; set; }
#endif
        /// <summary>The lastError property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastError { get; set; }
#nullable restore
#else
        public string LastError { get; set; }
#endif
        /// <summary>The processedDate property</summary>
        public DateTimeOffset? ProcessedDate { get; set; }
        /// <summary>The status property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.BrokerMessageHandlerStatus? Status { get; set; }
        /// <summary>The subscriptionKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubscriptionKey { get; set; }
#nullable restore
#else
        public string SubscriptionKey { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.BrokerMessageHandlerInfo"/> and sets the default values.
        /// </summary>
        public BrokerMessageHandlerInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.BrokerMessageHandlerInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.BrokerMessageHandlerInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.BrokerMessageHandlerInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attemptCount", n => { AttemptCount = n.GetIntValue(); } },
                { "handlerType", n => { HandlerType = n.GetStringValue(); } },
                { "lastError", n => { LastError = n.GetStringValue(); } },
                { "processedDate", n => { ProcessedDate = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.BrokerMessageHandlerStatus>(); } },
                { "subscriptionKey", n => { SubscriptionKey = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("attemptCount", AttemptCount);
            writer.WriteStringValue("handlerType", HandlerType);
            writer.WriteStringValue("lastError", LastError);
            writer.WriteDateTimeOffsetValue("processedDate", ProcessedDate);
            writer.WriteEnumValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.BrokerMessageHandlerStatus>("status", Status);
            writer.WriteStringValue("subscriptionKey", SubscriptionKey);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
