// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ChangeHistoryRestoreMode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ChangeSet")]
        #pragma warning disable CS1591
        ChangeSet,
        #pragma warning restore CS1591
        [EnumMember(Value = "PointInTime")]
        #pragma warning disable CS1591
        PointInTime,
        #pragma warning restore CS1591
    }
}
