// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models
{
    /// <summary>Logic operator for combining nested lofty filters</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FilterModel_filters_logic
    {
        [EnumMember(Value = "and")]
        #pragma warning disable CS1591
        And,
        #pragma warning restore CS1591
        [EnumMember(Value = "or")]
        #pragma warning disable CS1591
        Or,
        #pragma warning restore CS1591
    }
}
