// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum JobExecutionStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Started")]
        #pragma warning disable CS1591
        Started,
        #pragma warning restore CS1591
        [EnumMember(Value = "Completed")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
        [EnumMember(Value = "Failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "TimedOut")]
        #pragma warning disable CS1591
        TimedOut,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cancelled")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
        [EnumMember(Value = "Interrupted")]
        #pragma warning disable CS1591
        Interrupted,
        #pragma warning restore CS1591
        [EnumMember(Value = "Retried")]
        #pragma warning disable CS1591
        Retried,
        #pragma warning restore CS1591
    }
}
