// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class JobRun : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The category property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Category { get; set; }
#nullable restore
#else
        public string Category { get; set; }
#endif
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.JobRun_data? Data { get; set; }
#nullable restore
#else
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.JobRun_data Data { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The durationMs property</summary>
        public long? DurationMs { get; set; }
        /// <summary>The durationText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DurationText { get; set; }
#nullable restore
#else
        public string DurationText { get; set; }
#endif
        /// <summary>The endTime property</summary>
        public DateTimeOffset? EndTime { get; set; }
        /// <summary>The endTimeText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndTimeText { get; set; }
#nullable restore
#else
        public string EndTimeText { get; set; }
#endif
        /// <summary>The errorMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorMessage { get; set; }
#nullable restore
#else
        public string ErrorMessage { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The instanceName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InstanceName { get; set; }
#nullable restore
#else
        public string InstanceName { get; set; }
#endif
        /// <summary>The isRunning property</summary>
        public bool? IsRunning { get; set; }
        /// <summary>The jobGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JobGroup { get; set; }
#nullable restore
#else
        public string JobGroup { get; set; }
#endif
        /// <summary>The jobName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JobName { get; set; }
#nullable restore
#else
        public string JobName { get; set; }
#endif
        /// <summary>The priority property</summary>
        public int? Priority { get; set; }
        /// <summary>The result property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Result { get; set; }
#nullable restore
#else
        public string Result { get; set; }
#endif
        /// <summary>The retryCount property</summary>
        public int? RetryCount { get; set; }
        /// <summary>The scheduledTime property</summary>
        public DateTimeOffset? ScheduledTime { get; set; }
        /// <summary>The startTime property</summary>
        public DateTimeOffset? StartTime { get; set; }
        /// <summary>The startTimeText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartTimeText { get; set; }
#nullable restore
#else
        public string StartTimeText { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The triggerGroup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TriggerGroup { get; set; }
#nullable restore
#else
        public string TriggerGroup { get; set; }
#endif
        /// <summary>The triggerName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TriggerName { get; set; }
#nullable restore
#else
        public string TriggerName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.JobRun"/> and sets the default values.
        /// </summary>
        public JobRun()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.JobRun"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.JobRun CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.JobRun();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "category", n => { Category = n.GetStringValue(); } },
                { "data", n => { Data = n.GetObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.JobRun_data>(global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.JobRun_data.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "durationMs", n => { DurationMs = n.GetLongValue(); } },
                { "durationText", n => { DurationText = n.GetStringValue(); } },
                { "endTime", n => { EndTime = n.GetDateTimeOffsetValue(); } },
                { "endTimeText", n => { EndTimeText = n.GetStringValue(); } },
                { "errorMessage", n => { ErrorMessage = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "instanceName", n => { InstanceName = n.GetStringValue(); } },
                { "isRunning", n => { IsRunning = n.GetBoolValue(); } },
                { "jobGroup", n => { JobGroup = n.GetStringValue(); } },
                { "jobName", n => { JobName = n.GetStringValue(); } },
                { "priority", n => { Priority = n.GetIntValue(); } },
                { "result", n => { Result = n.GetStringValue(); } },
                { "retryCount", n => { RetryCount = n.GetIntValue(); } },
                { "scheduledTime", n => { ScheduledTime = n.GetDateTimeOffsetValue(); } },
                { "startTime", n => { StartTime = n.GetDateTimeOffsetValue(); } },
                { "startTimeText", n => { StartTimeText = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "triggerGroup", n => { TriggerGroup = n.GetStringValue(); } },
                { "triggerName", n => { TriggerName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("category", Category);
            writer.WriteObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.JobRun_data>("data", Data);
            writer.WriteStringValue("description", Description);
            writer.WriteLongValue("durationMs", DurationMs);
            writer.WriteStringValue("durationText", DurationText);
            writer.WriteDateTimeOffsetValue("endTime", EndTime);
            writer.WriteStringValue("endTimeText", EndTimeText);
            writer.WriteStringValue("errorMessage", ErrorMessage);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("instanceName", InstanceName);
            writer.WriteBoolValue("isRunning", IsRunning);
            writer.WriteStringValue("jobGroup", JobGroup);
            writer.WriteStringValue("jobName", JobName);
            writer.WriteIntValue("priority", Priority);
            writer.WriteStringValue("result", Result);
            writer.WriteIntValue("retryCount", RetryCount);
            writer.WriteDateTimeOffsetValue("scheduledTime", ScheduledTime);
            writer.WriteDateTimeOffsetValue("startTime", StartTime);
            writer.WriteStringValue("startTimeText", StartTimeText);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("triggerGroup", TriggerGroup);
            writer.WriteStringValue("triggerName", TriggerName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
