// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class JobSchedulerBatchModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The acceptedCount property</summary>
        public int? AcceptedCount { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The archivedCount property</summary>
        public int? ArchivedCount { get; set; }
        /// <summary>The batchId property</summary>
        public Guid? BatchId { get; set; }
        /// <summary>The cancelledCount property</summary>
        public int? CancelledCount { get; set; }
        /// <summary>The causationId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CausationId { get; set; }
#nullable restore
#else
        public string CausationId { get; set; }
#endif
        /// <summary>The childOccurrenceCount property</summary>
        public int? ChildOccurrenceCount { get; set; }
        /// <summary>The completedDate property</summary>
        public DateTimeOffset? CompletedDate { get; set; }
        /// <summary>The completionPolicy property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.JobBatchCompletionPolicy? CompletionPolicy { get; set; }
        /// <summary>The correlationId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CorrelationId { get; set; }
#nullable restore
#else
        public string CorrelationId { get; set; }
#endif
        /// <summary>The createdDate property</summary>
        public DateTimeOffset? CreatedDate { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The externalBatchId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalBatchId { get; set; }
#nullable restore
#else
        public string ExternalBatchId { get; set; }
#endif
        /// <summary>The failedCount property</summary>
        public int? FailedCount { get; set; }
        /// <summary>The idempotencyKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IdempotencyKey { get; set; }
#nullable restore
#else
        public string IdempotencyKey { get; set; }
#endif
        /// <summary>The propertyCount property</summary>
        public int? PropertyCount { get; set; }
        /// <summary>The propertyKeys property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? PropertyKeys { get; set; }
#nullable restore
#else
        public List<string> PropertyKeys { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.JobBatchStatus? Status { get; set; }
        /// <summary>The succeededCount property</summary>
        public int? SucceededCount { get; set; }
        /// <summary>The updatedDate property</summary>
        public DateTimeOffset? UpdatedDate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.JobSchedulerBatchModel"/> and sets the default values.
        /// </summary>
        public JobSchedulerBatchModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.JobSchedulerBatchModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.JobSchedulerBatchModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.JobSchedulerBatchModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "acceptedCount", n => { AcceptedCount = n.GetIntValue(); } },
                { "archivedCount", n => { ArchivedCount = n.GetIntValue(); } },
                { "batchId", n => { BatchId = n.GetGuidValue(); } },
                { "cancelledCount", n => { CancelledCount = n.GetIntValue(); } },
                { "causationId", n => { CausationId = n.GetStringValue(); } },
                { "childOccurrenceCount", n => { ChildOccurrenceCount = n.GetIntValue(); } },
                { "completedDate", n => { CompletedDate = n.GetDateTimeOffsetValue(); } },
                { "completionPolicy", n => { CompletionPolicy = n.GetEnumValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.JobBatchCompletionPolicy>(); } },
                { "correlationId", n => { CorrelationId = n.GetStringValue(); } },
                { "createdDate", n => { CreatedDate = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "externalBatchId", n => { ExternalBatchId = n.GetStringValue(); } },
                { "failedCount", n => { FailedCount = n.GetIntValue(); } },
                { "idempotencyKey", n => { IdempotencyKey = n.GetStringValue(); } },
                { "propertyCount", n => { PropertyCount = n.GetIntValue(); } },
                { "propertyKeys", n => { PropertyKeys = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "status", n => { Status = n.GetEnumValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.JobBatchStatus>(); } },
                { "succeededCount", n => { SucceededCount = n.GetIntValue(); } },
                { "updatedDate", n => { UpdatedDate = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("acceptedCount", AcceptedCount);
            writer.WriteIntValue("archivedCount", ArchivedCount);
            writer.WriteGuidValue("batchId", BatchId);
            writer.WriteIntValue("cancelledCount", CancelledCount);
            writer.WriteStringValue("causationId", CausationId);
            writer.WriteIntValue("childOccurrenceCount", ChildOccurrenceCount);
            writer.WriteDateTimeOffsetValue("completedDate", CompletedDate);
            writer.WriteEnumValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.JobBatchCompletionPolicy>("completionPolicy", CompletionPolicy);
            writer.WriteStringValue("correlationId", CorrelationId);
            writer.WriteDateTimeOffsetValue("createdDate", CreatedDate);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("externalBatchId", ExternalBatchId);
            writer.WriteIntValue("failedCount", FailedCount);
            writer.WriteStringValue("idempotencyKey", IdempotencyKey);
            writer.WriteIntValue("propertyCount", PropertyCount);
            writer.WriteCollectionOfPrimitiveValues<string>("propertyKeys", PropertyKeys);
            writer.WriteEnumValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.JobBatchStatus>("status", Status);
            writer.WriteIntValue("succeededCount", SucceededCount);
            writer.WriteDateTimeOffsetValue("updatedDate", UpdatedDate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
