// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LogEntryModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The correlationId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CorrelationId { get; set; }
#nullable restore
#else
        public string CorrelationId { get; set; }
#endif
        /// <summary>The exception property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Exception { get; set; }
#nullable restore
#else
        public string Exception { get; set; }
#endif
        /// <summary>The id property</summary>
        public long? Id { get; set; }
        /// <summary>The level property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Level { get; set; }
#nullable restore
#else
        public string Level { get; set; }
#endif
        /// <summary>The logEvents property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.LogEntryModel_logEvents? LogEvents { get; set; }
#nullable restore
#else
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.LogEntryModel_logEvents LogEvents { get; set; }
#endif
        /// <summary>The logKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LogKey { get; set; }
#nullable restore
#else
        public string LogKey { get; set; }
#endif
        /// <summary>The message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Message { get; set; }
#nullable restore
#else
        public string Message { get; set; }
#endif
        /// <summary>The messageTemplate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MessageTemplate { get; set; }
#nullable restore
#else
        public string MessageTemplate { get; set; }
#endif
        /// <summary>The moduleName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModuleName { get; set; }
#nullable restore
#else
        public string ModuleName { get; set; }
#endif
        /// <summary>The shortTypeName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShortTypeName { get; set; }
#nullable restore
#else
        public string ShortTypeName { get; set; }
#endif
        /// <summary>The spanId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpanId { get; set; }
#nullable restore
#else
        public string SpanId { get; set; }
#endif
        /// <summary>The threadId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThreadId { get; set; }
#nullable restore
#else
        public string ThreadId { get; set; }
#endif
        /// <summary>The timeStamp property</summary>
        public DateTimeOffset? TimeStamp { get; set; }
        /// <summary>The traceId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TraceId { get; set; }
#nullable restore
#else
        public string TraceId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.LogEntryModel"/> and sets the default values.
        /// </summary>
        public LogEntryModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.LogEntryModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.LogEntryModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.LogEntryModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "correlationId", n => { CorrelationId = n.GetStringValue(); } },
                { "exception", n => { Exception = n.GetStringValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "level", n => { Level = n.GetStringValue(); } },
                { "logEvents", n => { LogEvents = n.GetObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.LogEntryModel_logEvents>(global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.LogEntryModel_logEvents.CreateFromDiscriminatorValue); } },
                { "logKey", n => { LogKey = n.GetStringValue(); } },
                { "message", n => { Message = n.GetStringValue(); } },
                { "messageTemplate", n => { MessageTemplate = n.GetStringValue(); } },
                { "moduleName", n => { ModuleName = n.GetStringValue(); } },
                { "shortTypeName", n => { ShortTypeName = n.GetStringValue(); } },
                { "spanId", n => { SpanId = n.GetStringValue(); } },
                { "threadId", n => { ThreadId = n.GetStringValue(); } },
                { "timeStamp", n => { TimeStamp = n.GetDateTimeOffsetValue(); } },
                { "traceId", n => { TraceId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("correlationId", CorrelationId);
            writer.WriteStringValue("exception", Exception);
            writer.WriteLongValue("id", Id);
            writer.WriteStringValue("level", Level);
            writer.WriteObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.LogEntryModel_logEvents>("logEvents", LogEvents);
            writer.WriteStringValue("logKey", LogKey);
            writer.WriteStringValue("message", Message);
            writer.WriteStringValue("messageTemplate", MessageTemplate);
            writer.WriteStringValue("moduleName", ModuleName);
            writer.WriteStringValue("shortTypeName", ShortTypeName);
            writer.WriteStringValue("spanId", SpanId);
            writer.WriteStringValue("threadId", ThreadId);
            writer.WriteDateTimeOffsetValue("timeStamp", TimeStamp);
            writer.WriteStringValue("traceId", TraceId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
