// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum LogEntryExportFormat
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Csv")]
        #pragma warning disable CS1591
        Csv,
        #pragma warning restore CS1591
        [EnumMember(Value = "Json")]
        #pragma warning disable CS1591
        Json,
        #pragma warning restore CS1591
        [EnumMember(Value = "Txt")]
        #pragma warning disable CS1591
        Txt,
        #pragma warning restore CS1591
    }
}
