// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NotificationEmailAttachmentInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The contentId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentId { get; set; }
#nullable restore
#else
        public string ContentId { get; set; }
#endif
        /// <summary>The contentLength property</summary>
        public int? ContentLength { get; set; }
        /// <summary>The contentType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentType { get; set; }
#nullable restore
#else
        public string ContentType { get; set; }
#endif
        /// <summary>The emailMessageId property</summary>
        public Guid? EmailMessageId { get; set; }
        /// <summary>The fileName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileName { get; set; }
#nullable restore
#else
        public string FileName { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The isEmbedded property</summary>
        public bool? IsEmbedded { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.NotificationEmailAttachmentInfo"/> and sets the default values.
        /// </summary>
        public NotificationEmailAttachmentInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.NotificationEmailAttachmentInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.NotificationEmailAttachmentInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.NotificationEmailAttachmentInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "contentId", n => { ContentId = n.GetStringValue(); } },
                { "contentLength", n => { ContentLength = n.GetIntValue(); } },
                { "contentType", n => { ContentType = n.GetStringValue(); } },
                { "emailMessageId", n => { EmailMessageId = n.GetGuidValue(); } },
                { "fileName", n => { FileName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "isEmbedded", n => { IsEmbedded = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("contentId", ContentId);
            writer.WriteIntValue("contentLength", ContentLength);
            writer.WriteStringValue("contentType", ContentType);
            writer.WriteGuidValue("emailMessageId", EmailMessageId);
            writer.WriteStringValue("fileName", FileName);
            writer.WriteGuidValue("id", Id);
            writer.WriteBoolValue("isEmbedded", IsEmbedded);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
