// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NotificationEmailInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The archivedDate property</summary>
        public DateTimeOffset? ArchivedDate { get; set; }
        /// <summary>The attachmentCount property</summary>
        public int? AttachmentCount { get; set; }
        /// <summary>The attachments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.NotificationEmailAttachmentInfo>? Attachments { get; set; }
#nullable restore
#else
        public List<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.NotificationEmailAttachmentInfo> Attachments { get; set; }
#endif
        /// <summary>The bcc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Bcc { get; set; }
#nullable restore
#else
        public List<string> Bcc { get; set; }
#endif
        /// <summary>The cc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Cc { get; set; }
#nullable restore
#else
        public List<string> Cc { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The fromAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromAddress { get; set; }
#nullable restore
#else
        public string FromAddress { get; set; }
#endif
        /// <summary>The fromName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromName { get; set; }
#nullable restore
#else
        public string FromName { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The isArchived property</summary>
        public bool? IsArchived { get; set; }
        /// <summary>The isHtml property</summary>
        public bool? IsHtml { get; set; }
        /// <summary>The lockedBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LockedBy { get; set; }
#nullable restore
#else
        public string LockedBy { get; set; }
#endif
        /// <summary>The lockedUntil property</summary>
        public DateTimeOffset? LockedUntil { get; set; }
        /// <summary>The priority property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.EmailMessagePriority? Priority { get; set; }
        /// <summary>The processMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProcessMessage { get; set; }
#nullable restore
#else
        public string ProcessMessage { get; set; }
#endif
        /// <summary>The properties property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.NotificationEmailInfo_properties? Properties { get; set; }
#nullable restore
#else
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.NotificationEmailInfo_properties Properties { get; set; }
#endif
        /// <summary>The replyToAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReplyToAddress { get; set; }
#nullable restore
#else
        public string ReplyToAddress { get; set; }
#endif
        /// <summary>The replyToName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReplyToName { get; set; }
#nullable restore
#else
        public string ReplyToName { get; set; }
#endif
        /// <summary>The retryCount property</summary>
        public int? RetryCount { get; set; }
        /// <summary>The sentAt property</summary>
        public DateTimeOffset? SentAt { get; set; }
        /// <summary>The status property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.EmailMessageStatus? Status { get; set; }
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>The to property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? To { get; set; }
#nullable restore
#else
        public List<string> To { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.NotificationEmailInfo"/> and sets the default values.
        /// </summary>
        public NotificationEmailInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.NotificationEmailInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.NotificationEmailInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.NotificationEmailInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "archivedDate", n => { ArchivedDate = n.GetDateTimeOffsetValue(); } },
                { "attachmentCount", n => { AttachmentCount = n.GetIntValue(); } },
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.NotificationEmailAttachmentInfo>(global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.NotificationEmailAttachmentInfo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "bcc", n => { Bcc = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "cc", n => { Cc = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "fromAddress", n => { FromAddress = n.GetStringValue(); } },
                { "fromName", n => { FromName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "isArchived", n => { IsArchived = n.GetBoolValue(); } },
                { "isHtml", n => { IsHtml = n.GetBoolValue(); } },
                { "lockedBy", n => { LockedBy = n.GetStringValue(); } },
                { "lockedUntil", n => { LockedUntil = n.GetDateTimeOffsetValue(); } },
                { "priority", n => { Priority = n.GetEnumValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.EmailMessagePriority>(); } },
                { "processMessage", n => { ProcessMessage = n.GetStringValue(); } },
                { "properties", n => { Properties = n.GetObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.NotificationEmailInfo_properties>(global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.NotificationEmailInfo_properties.CreateFromDiscriminatorValue); } },
                { "replyToAddress", n => { ReplyToAddress = n.GetStringValue(); } },
                { "replyToName", n => { ReplyToName = n.GetStringValue(); } },
                { "retryCount", n => { RetryCount = n.GetIntValue(); } },
                { "sentAt", n => { SentAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.EmailMessageStatus>(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "to", n => { To = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("archivedDate", ArchivedDate);
            writer.WriteIntValue("attachmentCount", AttachmentCount);
            writer.WriteCollectionOfObjectValues<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.NotificationEmailAttachmentInfo>("attachments", Attachments);
            writer.WriteCollectionOfPrimitiveValues<string>("bcc", Bcc);
            writer.WriteCollectionOfPrimitiveValues<string>("cc", Cc);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("fromAddress", FromAddress);
            writer.WriteStringValue("fromName", FromName);
            writer.WriteGuidValue("id", Id);
            writer.WriteBoolValue("isArchived", IsArchived);
            writer.WriteBoolValue("isHtml", IsHtml);
            writer.WriteStringValue("lockedBy", LockedBy);
            writer.WriteDateTimeOffsetValue("lockedUntil", LockedUntil);
            writer.WriteEnumValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.EmailMessagePriority>("priority", Priority);
            writer.WriteStringValue("processMessage", ProcessMessage);
            writer.WriteObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.NotificationEmailInfo_properties>("properties", Properties);
            writer.WriteStringValue("replyToAddress", ReplyToAddress);
            writer.WriteStringValue("replyToName", ReplyToName);
            writer.WriteIntValue("retryCount", RetryCount);
            writer.WriteDateTimeOffsetValue("sentAt", SentAt);
            writer.WriteEnumValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.EmailMessageStatus>("status", Status);
            writer.WriteStringValue("subject", Subject);
            writer.WriteCollectionOfPrimitiveValues<string>("to", To);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
