// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OrchestrationMetricsModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The averageDurationSeconds property</summary>
        public double? AverageDurationSeconds { get; set; }
        /// <summary>The cancelledCount property</summary>
        public long? CancelledCount { get; set; }
        /// <summary>The completedCount property</summary>
        public long? CompletedCount { get; set; }
        /// <summary>The countsByOrchestration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.OrchestrationMetricsModel_countsByOrchestration? CountsByOrchestration { get; set; }
#nullable restore
#else
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.OrchestrationMetricsModel_countsByOrchestration CountsByOrchestration { get; set; }
#endif
        /// <summary>The countsByState property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.OrchestrationMetricsModel_countsByState? CountsByState { get; set; }
#nullable restore
#else
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.OrchestrationMetricsModel_countsByState CountsByState { get; set; }
#endif
        /// <summary>The failedCount property</summary>
        public long? FailedCount { get; set; }
        /// <summary>The oldestWaitingStartedUtc property</summary>
        public DateTimeOffset? OldestWaitingStartedUtc { get; set; }
        /// <summary>The pausedCount property</summary>
        public long? PausedCount { get; set; }
        /// <summary>The runningCount property</summary>
        public long? RunningCount { get; set; }
        /// <summary>The terminatedCount property</summary>
        public long? TerminatedCount { get; set; }
        /// <summary>The totalCount property</summary>
        public long? TotalCount { get; set; }
        /// <summary>The waitingCount property</summary>
        public long? WaitingCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.OrchestrationMetricsModel"/> and sets the default values.
        /// </summary>
        public OrchestrationMetricsModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.OrchestrationMetricsModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.OrchestrationMetricsModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.OrchestrationMetricsModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "averageDurationSeconds", n => { AverageDurationSeconds = n.GetDoubleValue(); } },
                { "cancelledCount", n => { CancelledCount = n.GetLongValue(); } },
                { "completedCount", n => { CompletedCount = n.GetLongValue(); } },
                { "countsByOrchestration", n => { CountsByOrchestration = n.GetObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.OrchestrationMetricsModel_countsByOrchestration>(global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.OrchestrationMetricsModel_countsByOrchestration.CreateFromDiscriminatorValue); } },
                { "countsByState", n => { CountsByState = n.GetObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.OrchestrationMetricsModel_countsByState>(global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.OrchestrationMetricsModel_countsByState.CreateFromDiscriminatorValue); } },
                { "failedCount", n => { FailedCount = n.GetLongValue(); } },
                { "oldestWaitingStartedUtc", n => { OldestWaitingStartedUtc = n.GetDateTimeOffsetValue(); } },
                { "pausedCount", n => { PausedCount = n.GetLongValue(); } },
                { "runningCount", n => { RunningCount = n.GetLongValue(); } },
                { "terminatedCount", n => { TerminatedCount = n.GetLongValue(); } },
                { "totalCount", n => { TotalCount = n.GetLongValue(); } },
                { "waitingCount", n => { WaitingCount = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("averageDurationSeconds", AverageDurationSeconds);
            writer.WriteLongValue("cancelledCount", CancelledCount);
            writer.WriteLongValue("completedCount", CompletedCount);
            writer.WriteObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.OrchestrationMetricsModel_countsByOrchestration>("countsByOrchestration", CountsByOrchestration);
            writer.WriteObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.OrchestrationMetricsModel_countsByState>("countsByState", CountsByState);
            writer.WriteLongValue("failedCount", FailedCount);
            writer.WriteDateTimeOffsetValue("oldestWaitingStartedUtc", OldestWaitingStartedUtc);
            writer.WriteLongValue("pausedCount", PausedCount);
            writer.WriteLongValue("runningCount", RunningCount);
            writer.WriteLongValue("terminatedCount", TerminatedCount);
            writer.WriteLongValue("totalCount", TotalCount);
            writer.WriteLongValue("waitingCount", WaitingCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
