// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OrchestrationInstanceModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The completedUtc property</summary>
        public DateTimeOffset? CompletedUtc { get; set; }
        /// <summary>The concurrencyKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConcurrencyKey { get; set; }
#nullable restore
#else
        public string ConcurrencyKey { get; set; }
#endif
        /// <summary>The correlationId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CorrelationId { get; set; }
#nullable restore
#else
        public string CorrelationId { get; set; }
#endif
        /// <summary>The createdBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The createdDate property</summary>
        public DateTimeOffset? CreatedDate { get; set; }
        /// <summary>The currentActivity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrentActivity { get; set; }
#nullable restore
#else
        public string CurrentActivity { get; set; }
#endif
        /// <summary>The currentState property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CurrentState { get; set; }
#nullable restore
#else
        public string CurrentState { get; set; }
#endif
        /// <summary>The instanceId property</summary>
        public Guid? InstanceId { get; set; }
        /// <summary>The lastUpdatedUtc property</summary>
        public DateTimeOffset? LastUpdatedUtc { get; set; }
        /// <summary>The orchestrationName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrchestrationName { get; set; }
#nullable restore
#else
        public string OrchestrationName { get; set; }
#endif
        /// <summary>The startedUtc property</summary>
        public DateTimeOffset? StartedUtc { get; set; }
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The updatedBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedBy { get; set; }
#nullable restore
#else
        public string UpdatedBy { get; set; }
#endif
        /// <summary>The updatedDate property</summary>
        public DateTimeOffset? UpdatedDate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.OrchestrationInstanceModel"/> and sets the default values.
        /// </summary>
        public OrchestrationInstanceModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.OrchestrationInstanceModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.OrchestrationInstanceModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.OrchestrationInstanceModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "completedUtc", n => { CompletedUtc = n.GetDateTimeOffsetValue(); } },
                { "concurrencyKey", n => { ConcurrencyKey = n.GetStringValue(); } },
                { "correlationId", n => { CorrelationId = n.GetStringValue(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "createdDate", n => { CreatedDate = n.GetDateTimeOffsetValue(); } },
                { "currentActivity", n => { CurrentActivity = n.GetStringValue(); } },
                { "currentState", n => { CurrentState = n.GetStringValue(); } },
                { "instanceId", n => { InstanceId = n.GetGuidValue(); } },
                { "lastUpdatedUtc", n => { LastUpdatedUtc = n.GetDateTimeOffsetValue(); } },
                { "orchestrationName", n => { OrchestrationName = n.GetStringValue(); } },
                { "startedUtc", n => { StartedUtc = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "updatedBy", n => { UpdatedBy = n.GetStringValue(); } },
                { "updatedDate", n => { UpdatedDate = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("completedUtc", CompletedUtc);
            writer.WriteStringValue("concurrencyKey", ConcurrencyKey);
            writer.WriteStringValue("correlationId", CorrelationId);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteDateTimeOffsetValue("createdDate", CreatedDate);
            writer.WriteStringValue("currentActivity", CurrentActivity);
            writer.WriteStringValue("currentState", CurrentState);
            writer.WriteGuidValue("instanceId", InstanceId);
            writer.WriteDateTimeOffsetValue("lastUpdatedUtc", LastUpdatedUtc);
            writer.WriteStringValue("orchestrationName", OrchestrationName);
            writer.WriteDateTimeOffsetValue("startedUtc", StartedUtc);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("updatedBy", UpdatedBy);
            writer.WriteDateTimeOffsetValue("updatedDate", UpdatedDate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
