// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SystemInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The configuration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_configuration? Configuration { get; set; }
#nullable restore
#else
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_configuration Configuration { get; set; }
#endif
        /// <summary>The customMetadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_customMetadata? CustomMetadata { get; set; }
#nullable restore
#else
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_customMetadata CustomMetadata { get; set; }
#endif
        /// <summary>The memory property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_memory? Memory { get; set; }
#nullable restore
#else
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_memory Memory { get; set; }
#endif
        /// <summary>The request property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_request? Request { get; set; }
#nullable restore
#else
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_request Request { get; set; }
#endif
        /// <summary>The runtime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_runtime? Runtime { get; set; }
#nullable restore
#else
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_runtime Runtime { get; set; }
#endif
        /// <summary>The uptime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uptime { get; set; }
#nullable restore
#else
        public string Uptime { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo"/> and sets the default values.
        /// </summary>
        public SystemInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "configuration", n => { Configuration = n.GetObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_configuration>(global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_configuration.CreateFromDiscriminatorValue); } },
                { "customMetadata", n => { CustomMetadata = n.GetObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_customMetadata>(global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_customMetadata.CreateFromDiscriminatorValue); } },
                { "memory", n => { Memory = n.GetObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_memory>(global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_memory.CreateFromDiscriminatorValue); } },
                { "request", n => { Request = n.GetObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_request>(global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_request.CreateFromDiscriminatorValue); } },
                { "runtime", n => { Runtime = n.GetObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_runtime>(global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_runtime.CreateFromDiscriminatorValue); } },
                { "uptime", n => { Uptime = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_configuration>("configuration", Configuration);
            writer.WriteObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_customMetadata>("customMetadata", CustomMetadata);
            writer.WriteObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_memory>("memory", Memory);
            writer.WriteObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_request>("request", Request);
            writer.WriteObjectValue<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.SystemInfo_runtime>("runtime", Runtime);
            writer.WriteStringValue("uptime", Uptime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
