namespace BridgingIT.DevKit.Application.Storage;

public sealed class DocumentTestPage<T> { public IReadOnlyList<T> Items { get; init; } = []; public string ContinuationToken { get; init; } public bool HasMore => !string.IsNullOrWhiteSpace(this.ContinuationToken); }
public static class DocumentStorageTestCompatibilityExtensions
{
    public static async Task<Result<T>> GetResultAsync<T>(this IDocumentStoreClient<T> client, DocumentKey key, CancellationToken ct = default) where T : class, new() { var r = await client.GetAsync(key, ct); return r.IsFailure ? r.Wrap<T>() : Result<T>.Success(r.Value.Value); }
    public static async Task<Result<DocumentTestPage<T>>> FindPageResultAsync<T>(this IDocumentStoreClient<T> client, DocumentQuery query, CancellationToken ct = default) where T : class, new() { var r = await client.FindPageAsync(query, ct); return r.IsFailure ? r.Wrap<DocumentTestPage<T>>() : Result<DocumentTestPage<T>>.Success(new() { Items = r.Value.Items.Select(x => x.Value).ToArray(), ContinuationToken = r.Value.ContinuationToken }); }
    public static Task<Result<DocumentKeyPage>> ListPageResultAsync<T>(this IDocumentStoreClient<T> client, DocumentQuery query, CancellationToken ct = default) where T : class, new() => client.ListPageAsync(query, ct);
    public static Task<Result<long>> CountResultAsync<T>(this IDocumentStoreClient<T> client, DocumentCountQuery query, CancellationToken ct = default) where T : class, new() => client.CountAsync(query, ct);
    public static Task<Result<bool>> ExistsResultAsync<T>(this IDocumentStoreClient<T> client, DocumentKey key, CancellationToken ct = default) where T : class, new() => client.ExistsAsync(key, ct);
    public static async Task<Result> UpsertResultAsync<T>(this IDocumentStoreClient<T> client, DocumentKey key, T value, CancellationToken ct = default) where T : class, new() { var r = await client.UpsertAsync(key, value, cancellationToken: ct); return r.IsSuccess ? Result.Success() : Result.Failure().WithMessages(r.Messages); }
    public static Task<Result> DeleteResultAsync<T>(this IDocumentStoreClient<T> client, DocumentKey key, CancellationToken ct = default) where T : class, new() => client.DeleteAsync(key, cancellationToken: ct);
    public static async Task<Result<T>> GetResultAsync<T>(this IDocumentStoreProvider provider, DocumentKey key, CancellationToken ct = default) where T : class, new() { var r = await new DocumentStoreClient<T>(provider).GetAsync(key, ct); return r.IsFailure ? r.Wrap<T>() : Result<T>.Success(r.Value.Value); }
    public static async Task<Result<DocumentTestPage<T>>> FindPageResultAsync<T>(this IDocumentStoreProvider provider, DocumentQuery query, CancellationToken ct = default) where T : class, new() { var r = await new DocumentStoreClient<T>(provider, options: new() { AllowFullScans = true }).FindPageAsync(query, ct); return r.IsFailure ? r.Wrap<DocumentTestPage<T>>() : Result<DocumentTestPage<T>>.Success(new() { Items = r.Value.Items.Select(x => x.Value).ToArray(), ContinuationToken = r.Value.ContinuationToken }); }
    public static Task<Result<DocumentKeyPage>> ListPageResultAsync<T>(this IDocumentStoreProvider provider, DocumentQuery query, CancellationToken ct = default) where T : class, new() => new DocumentStoreClient<T>(provider, options: new() { AllowFullScans = true }).ListPageAsync(query, ct);
    public static Task<Result<long>> CountResultAsync<T>(this IDocumentStoreProvider provider, DocumentCountQuery query, CancellationToken ct = default) where T : class, new() => new DocumentStoreClient<T>(provider, options: new() { AllowFullScans = true }).CountAsync(query, ct);
    public static Task<Result<bool>> ExistsResultAsync<T>(this IDocumentStoreProvider provider, DocumentKey key, CancellationToken ct = default) where T : class, new() => new DocumentStoreClient<T>(provider).ExistsAsync(key, ct);
    public static async Task<Result> UpsertResultAsync<T>(this IDocumentStoreProvider provider, DocumentKey key, T value, CancellationToken ct = default) where T : class, new() { var r = await new DocumentStoreClient<T>(provider).UpsertAsync(key, value, cancellationToken: ct); return r.IsSuccess ? Result.Success() : Result.Failure().WithMessages(r.Messages); }
    public static Task<Result> DeleteResultAsync<T>(this IDocumentStoreProvider provider, DocumentKey key, CancellationToken ct = default) where T : class, new() => new DocumentStoreClient<T>(provider).DeleteAsync(key, cancellationToken: ct);
}
