// <auto-generated/>
#pragma warning disable CS0618
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Jobs.Maintenance.DetectOrphanedRuntimeState;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Jobs.Maintenance.PurgeHistory;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Jobs.Maintenance.RecoverStuckOccurrences;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Jobs.Maintenance.ReleaseExpiredLeases;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Jobs.Maintenance
{
    /// <summary>
    /// Builds and executes requests for operations under \_bdk\api\jobs\maintenance
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MaintenanceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The detectOrphanedRuntimeState property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Jobs.Maintenance.DetectOrphanedRuntimeState.DetectOrphanedRuntimeStateRequestBuilder DetectOrphanedRuntimeState
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Jobs.Maintenance.DetectOrphanedRuntimeState.DetectOrphanedRuntimeStateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The purgeHistory property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Jobs.Maintenance.PurgeHistory.PurgeHistoryRequestBuilder PurgeHistory
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Jobs.Maintenance.PurgeHistory.PurgeHistoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recoverStuckOccurrences property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Jobs.Maintenance.RecoverStuckOccurrences.RecoverStuckOccurrencesRequestBuilder RecoverStuckOccurrences
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Jobs.Maintenance.RecoverStuckOccurrences.RecoverStuckOccurrencesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The releaseExpiredLeases property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Jobs.Maintenance.ReleaseExpiredLeases.ReleaseExpiredLeasesRequestBuilder ReleaseExpiredLeases
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Jobs.Maintenance.ReleaseExpiredLeases.ReleaseExpiredLeasesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Jobs.Maintenance.MaintenanceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MaintenanceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/_bdk/api/jobs/maintenance", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Jobs.Maintenance.MaintenanceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MaintenanceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/_bdk/api/jobs/maintenance", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
