// MIT-License
// Copyright BridgingIT GmbH - All Rights Reserved
// Use of this source code is governed by an MIT-style license that can be
// found in the LICENSE file at https://github.com/bridgingit/bitdevkit/license

namespace BridgingIT.DevKit.Examples.WeatherForecast.Infrastructure;

// classes generated by https://app.quicktype.io/
public class Temperatures
{
    [Newtonsoft.Json.JsonProperty("lat")]
    [System.Text.Json.Serialization.JsonPropertyName("lat")]
    public double Lat { get; set; }

    [Newtonsoft.Json.JsonProperty("lon")]
    [System.Text.Json.Serialization.JsonPropertyName("lon")]
    public double Lon { get; set; }

    [Newtonsoft.Json.JsonProperty("timezone")]
    [System.Text.Json.Serialization.JsonPropertyName("timezone")]
    public string Timezone { get; set; }

    [Newtonsoft.Json.JsonProperty("current")]
    [System.Text.Json.Serialization.JsonPropertyName("current")]
    public Current Current { get; set; }

    [Newtonsoft.Json.JsonProperty("hourly")]
    [System.Text.Json.Serialization.JsonPropertyName("hourly")]
    public Hourly[] Hourly { get; set; }

    [Newtonsoft.Json.JsonProperty("daily")]
    [System.Text.Json.Serialization.JsonPropertyName("daily")]
    public Daily[] Daily { get; set; }
}

public class Current
{
    [Newtonsoft.Json.JsonProperty("dt")]
    [System.Text.Json.Serialization.JsonPropertyName("dt")]
    public long Dt { get; set; }

    [Newtonsoft.Json.JsonProperty("sunrise")]
    [System.Text.Json.Serialization.JsonPropertyName("sunrise")]
    public long Sunrise { get; set; }

    [Newtonsoft.Json.JsonProperty("sunset")]
    [System.Text.Json.Serialization.JsonPropertyName("sunset")]
    public long Sunset { get; set; }

    [Newtonsoft.Json.JsonProperty("temp")]
    [System.Text.Json.Serialization.JsonPropertyName("temp")]
    public double Temp { get; set; }

    [Newtonsoft.Json.JsonProperty("feels_like")]
    [System.Text.Json.Serialization.JsonPropertyName("feels_like")]
    public double FeelsLike { get; set; }

    [Newtonsoft.Json.JsonProperty("pressure")]
    [System.Text.Json.Serialization.JsonPropertyName("pressure")]
    public long Pressure { get; set; }

    [Newtonsoft.Json.JsonProperty("humidity")]
    [System.Text.Json.Serialization.JsonPropertyName("humidity")]
    public long Humidity { get; set; }

    [Newtonsoft.Json.JsonProperty("dew_point")]
    [System.Text.Json.Serialization.JsonPropertyName("dew_point")]
    public double DewPoint { get; set; }

    [Newtonsoft.Json.JsonProperty("uvi")]
    [System.Text.Json.Serialization.JsonPropertyName("uvi")]
    public double Uvi { get; set; }

    [Newtonsoft.Json.JsonProperty("clouds")]
    [System.Text.Json.Serialization.JsonPropertyName("clouds")]
    public long Clouds { get; set; }

    [Newtonsoft.Json.JsonProperty("visibility")]
    [System.Text.Json.Serialization.JsonPropertyName("visibility")]
    public long Visibility { get; set; }

    [Newtonsoft.Json.JsonProperty("wind_speed")]
    [System.Text.Json.Serialization.JsonPropertyName("wind_speed")]
    public double WindSpeed { get; set; }

    [Newtonsoft.Json.JsonProperty("wind_deg")]
    [System.Text.Json.Serialization.JsonPropertyName("wind_deg")]
    public long WindDeg { get; set; }

    [Newtonsoft.Json.JsonProperty("weather")]
    [System.Text.Json.Serialization.JsonPropertyName("weather")]
    public Weather[] Weather { get; set; }

    [Newtonsoft.Json.JsonProperty("rain")]
    [System.Text.Json.Serialization.JsonPropertyName("rain")]
    public CurrentRain Rain { get; set; }
}

public class CurrentRain
{
}

public class Weather
{
    [Newtonsoft.Json.JsonProperty("id")]
    [System.Text.Json.Serialization.JsonPropertyName("id")]
    public long Id { get; set; }

    [Newtonsoft.Json.JsonProperty("main")]
    [System.Text.Json.Serialization.JsonPropertyName("main")]
    public string Main { get; set; }

    [Newtonsoft.Json.JsonProperty("description")]
    [System.Text.Json.Serialization.JsonPropertyName("description")]
    public string Description { get; set; }

    [Newtonsoft.Json.JsonProperty("icon")]
    [System.Text.Json.Serialization.JsonPropertyName("icon")]
    public string Icon { get; set; }
}

public class Daily
{
    [Newtonsoft.Json.JsonProperty("dt")]
    [System.Text.Json.Serialization.JsonPropertyName("dt")]
    public long Dt { get; set; }

    [Newtonsoft.Json.JsonProperty("sunrise")]
    [System.Text.Json.Serialization.JsonPropertyName("sunrise")]
    public long Sunrise { get; set; }

    [Newtonsoft.Json.JsonProperty("sunset")]
    [System.Text.Json.Serialization.JsonPropertyName("sunset")]
    public long Sunset { get; set; }

    [Newtonsoft.Json.JsonProperty("temp")]
    [System.Text.Json.Serialization.JsonPropertyName("temp")]
    public Temp Temp { get; set; }

    [Newtonsoft.Json.JsonProperty("feels_like")]
    [System.Text.Json.Serialization.JsonPropertyName("feels_like")]
    public FeelsLike FeelsLike { get; set; }

    [Newtonsoft.Json.JsonProperty("pressure")]
    [System.Text.Json.Serialization.JsonPropertyName("pressure")]
    public long Pressure { get; set; }

    [Newtonsoft.Json.JsonProperty("humidity")]
    [System.Text.Json.Serialization.JsonPropertyName("humidity")]
    public long Humidity { get; set; }

    [Newtonsoft.Json.JsonProperty("dew_point")]
    [System.Text.Json.Serialization.JsonPropertyName("dew_point")]
    public double DewPoint { get; set; }

    [Newtonsoft.Json.JsonProperty("wind_speed")]
    [System.Text.Json.Serialization.JsonPropertyName("wind_speed")]
    public double WindSpeed { get; set; }

    [Newtonsoft.Json.JsonProperty("wind_deg")]
    [System.Text.Json.Serialization.JsonPropertyName("wind_deg")]
    public long WindDeg { get; set; }

    [Newtonsoft.Json.JsonProperty("weather")]
    [System.Text.Json.Serialization.JsonPropertyName("weather")]
    public Weather[] Weather { get; set; }

    [Newtonsoft.Json.JsonProperty("clouds")]
    [System.Text.Json.Serialization.JsonPropertyName("clouds")]
    public long Clouds { get; set; }

    [Newtonsoft.Json.JsonProperty("rain", NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.Text.Json.Serialization.JsonPropertyName("rain")]
    public double? Rain { get; set; }

    [Newtonsoft.Json.JsonProperty("uvi")]
    [System.Text.Json.Serialization.JsonPropertyName("uvi")]
    public double Uvi { get; set; }
}

public class FeelsLike
{
    [Newtonsoft.Json.JsonProperty("day")]
    [System.Text.Json.Serialization.JsonPropertyName("day")]
    public double Day { get; set; }

    [Newtonsoft.Json.JsonProperty("night")]
    [System.Text.Json.Serialization.JsonPropertyName("night")]
    public double Night { get; set; }

    [Newtonsoft.Json.JsonProperty("eve")]
    [System.Text.Json.Serialization.JsonPropertyName("eve")]
    public double Eve { get; set; }

    [Newtonsoft.Json.JsonProperty("morn")]
    [System.Text.Json.Serialization.JsonPropertyName("morn")]
    public double Morn { get; set; }
}

public class Temp
{
    [Newtonsoft.Json.JsonProperty("day")]
    [System.Text.Json.Serialization.JsonPropertyName("day")]
    public double Day { get; set; }

    [Newtonsoft.Json.JsonProperty("min")]
    [System.Text.Json.Serialization.JsonPropertyName("min")]
    public double Min { get; set; }

    [Newtonsoft.Json.JsonProperty("max")]
    [System.Text.Json.Serialization.JsonPropertyName("max")]
    public double Max { get; set; }

    [Newtonsoft.Json.JsonProperty("night")]
    [System.Text.Json.Serialization.JsonPropertyName("night")]
    public double Night { get; set; }

    [Newtonsoft.Json.JsonProperty("eve")]
    [System.Text.Json.Serialization.JsonPropertyName("eve")]
    public double Eve { get; set; }

    [Newtonsoft.Json.JsonProperty("morn")]
    [System.Text.Json.Serialization.JsonPropertyName("morn")]
    public double Morn { get; set; }
}

public class Hourly
{
    [Newtonsoft.Json.JsonProperty("dt")]
    [System.Text.Json.Serialization.JsonPropertyName("dt")]
    public long Dt { get; set; }

    [Newtonsoft.Json.JsonProperty("temp")]
    [System.Text.Json.Serialization.JsonPropertyName("temp")]
    public double Temp { get; set; }

    [Newtonsoft.Json.JsonProperty("feels_like")]
    [System.Text.Json.Serialization.JsonPropertyName("feels_like")]
    public double FeelsLike { get; set; }

    [Newtonsoft.Json.JsonProperty("pressure")]
    [System.Text.Json.Serialization.JsonPropertyName("pressure")]
    public long Pressure { get; set; }

    [Newtonsoft.Json.JsonProperty("humidity")]
    [System.Text.Json.Serialization.JsonPropertyName("humidity")]
    public long Humidity { get; set; }

    [Newtonsoft.Json.JsonProperty("dew_point")]
    [System.Text.Json.Serialization.JsonPropertyName("dew_point")]
    public double DewPoint { get; set; }

    [Newtonsoft.Json.JsonProperty("clouds")]
    [System.Text.Json.Serialization.JsonPropertyName("clouds")]
    public long Clouds { get; set; }

    [Newtonsoft.Json.JsonProperty("wind_speed")]
    [System.Text.Json.Serialization.JsonPropertyName("wind_speed")]
    public double WindSpeed { get; set; }

    [Newtonsoft.Json.JsonProperty("wind_deg")]
    [System.Text.Json.Serialization.JsonPropertyName("wind_deg")]
    public long WindDeg { get; set; }

    [Newtonsoft.Json.JsonProperty("weather")]
    [System.Text.Json.Serialization.JsonPropertyName("weather")]
    public Weather[] Weather { get; set; }

    [Newtonsoft.Json.JsonProperty("rain", NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.Text.Json.Serialization.JsonPropertyName("rain")]
    public HourlyRain Rain { get; set; }
}

public class HourlyRain
{
    [Newtonsoft.Json.JsonProperty("1h")]
    [System.Text.Json.Serialization.JsonPropertyName("1h")]
    public double The1H { get; set; }
}
