// MIT-License
// Copyright BridgingIT GmbH - All Rights Reserved
// Use of this source code is governed by an MIT-style license that can be
// found in the LICENSE file at https://github.com/bridgingit/bitdevkit/license

namespace BridgingIT.DevKit.Examples.WeatherForecast.Infrastructure;

using System.Text.Json.Serialization;
using Newtonsoft.Json;

// classes generated by https://app.quicktype.io/
public class Temperatures
{
    [JsonProperty("lat")]
    [JsonPropertyName("lat")]
    public double Lat { get; set; }

    [JsonProperty("lon")]
    [JsonPropertyName("lon")]
    public double Lon { get; set; }

    [JsonProperty("timezone")]
    [JsonPropertyName("timezone")]
    public string Timezone { get; set; }

    [JsonProperty("current")]
    [JsonPropertyName("current")]
    public Current Current { get; set; }

    [JsonProperty("hourly")]
    [JsonPropertyName("hourly")]
    public Hourly[] Hourly { get; set; }

    [JsonProperty("daily")]
    [JsonPropertyName("daily")]
    public Daily[] Daily { get; set; }
}

public class Current
{
    [JsonProperty("dt")]
    [JsonPropertyName("dt")]
    public long Dt { get; set; }

    [JsonProperty("sunrise")]
    [JsonPropertyName("sunrise")]
    public long Sunrise { get; set; }

    [JsonProperty("sunset")]
    [JsonPropertyName("sunset")]
    public long Sunset { get; set; }

    [JsonProperty("temp")]
    [JsonPropertyName("temp")]
    public double Temp { get; set; }

    [JsonProperty("feels_like")]
    [JsonPropertyName("feels_like")]
    public double FeelsLike { get; set; }

    [JsonProperty("pressure")]
    [JsonPropertyName("pressure")]
    public long Pressure { get; set; }

    [JsonProperty("humidity")]
    [JsonPropertyName("humidity")]
    public long Humidity { get; set; }

    [JsonProperty("dew_point")]
    [JsonPropertyName("dew_point")]
    public double DewPoint { get; set; }

    [JsonProperty("uvi")]
    [JsonPropertyName("uvi")]
    public double Uvi { get; set; }

    [JsonProperty("clouds")]
    [JsonPropertyName("clouds")]
    public long Clouds { get; set; }

    [JsonProperty("visibility")]
    [JsonPropertyName("visibility")]
    public long Visibility { get; set; }

    [JsonProperty("wind_speed")]
    [JsonPropertyName("wind_speed")]
    public double WindSpeed { get; set; }

    [JsonProperty("wind_deg")]
    [JsonPropertyName("wind_deg")]
    public long WindDeg { get; set; }

    [JsonProperty("weather")]
    [JsonPropertyName("weather")]
    public Weather[] Weather { get; set; }

    [JsonProperty("rain")]
    [JsonPropertyName("rain")]
    public CurrentRain Rain { get; set; }
}

public class CurrentRain;

public class Weather
{
    [JsonProperty("id")]
    [JsonPropertyName("id")]
    public long Id { get; set; }

    [JsonProperty("main")]
    [JsonPropertyName("main")]
    public string Main { get; set; }

    [JsonProperty("description")]
    [JsonPropertyName("description")]
    public string Description { get; set; }

    [JsonProperty("icon")]
    [JsonPropertyName("icon")]
    public string Icon { get; set; }
}

public class Daily
{
    [JsonProperty("dt")]
    [JsonPropertyName("dt")]
    public long Dt { get; set; }

    [JsonProperty("sunrise")]
    [JsonPropertyName("sunrise")]
    public long Sunrise { get; set; }

    [JsonProperty("sunset")]
    [JsonPropertyName("sunset")]
    public long Sunset { get; set; }

    [JsonProperty("temp")]
    [JsonPropertyName("temp")]
    public Temp Temp { get; set; }

    [JsonProperty("feels_like")]
    [JsonPropertyName("feels_like")]
    public FeelsLike FeelsLike { get; set; }

    [JsonProperty("pressure")]
    [JsonPropertyName("pressure")]
    public long Pressure { get; set; }

    [JsonProperty("humidity")]
    [JsonPropertyName("humidity")]
    public long Humidity { get; set; }

    [JsonProperty("dew_point")]
    [JsonPropertyName("dew_point")]
    public double DewPoint { get; set; }

    [JsonProperty("wind_speed")]
    [JsonPropertyName("wind_speed")]
    public double WindSpeed { get; set; }

    [JsonProperty("wind_deg")]
    [JsonPropertyName("wind_deg")]
    public long WindDeg { get; set; }

    [JsonProperty("weather")]
    [JsonPropertyName("weather")]
    public Weather[] Weather { get; set; }

    [JsonProperty("clouds")]
    [JsonPropertyName("clouds")]
    public long Clouds { get; set; }

    [JsonProperty("rain", NullValueHandling = NullValueHandling.Ignore)]
    [JsonPropertyName("rain")]
    public double? Rain { get; set; }

    [JsonProperty("uvi")]
    [JsonPropertyName("uvi")]
    public double Uvi { get; set; }
}

public class FeelsLike
{
    [JsonProperty("day")]
    [JsonPropertyName("day")]
    public double Day { get; set; }

    [JsonProperty("night")]
    [JsonPropertyName("night")]
    public double Night { get; set; }

    [JsonProperty("eve")]
    [JsonPropertyName("eve")]
    public double Eve { get; set; }

    [JsonProperty("morn")]
    [JsonPropertyName("morn")]
    public double Morn { get; set; }
}

public class Temp
{
    [JsonProperty("day")]
    [JsonPropertyName("day")]
    public double Day { get; set; }

    [JsonProperty("min")]
    [JsonPropertyName("min")]
    public double Min { get; set; }

    [JsonProperty("max")]
    [JsonPropertyName("max")]
    public double Max { get; set; }

    [JsonProperty("night")]
    [JsonPropertyName("night")]
    public double Night { get; set; }

    [JsonProperty("eve")]
    [JsonPropertyName("eve")]
    public double Eve { get; set; }

    [JsonProperty("morn")]
    [JsonPropertyName("morn")]
    public double Morn { get; set; }
}

public class Hourly
{
    [JsonProperty("dt")]
    [JsonPropertyName("dt")]
    public long Dt { get; set; }

    [JsonProperty("temp")]
    [JsonPropertyName("temp")]
    public double Temp { get; set; }

    [JsonProperty("feels_like")]
    [JsonPropertyName("feels_like")]
    public double FeelsLike { get; set; }

    [JsonProperty("pressure")]
    [JsonPropertyName("pressure")]
    public long Pressure { get; set; }

    [JsonProperty("humidity")]
    [JsonPropertyName("humidity")]
    public long Humidity { get; set; }

    [JsonProperty("dew_point")]
    [JsonPropertyName("dew_point")]
    public double DewPoint { get; set; }

    [JsonProperty("clouds")]
    [JsonPropertyName("clouds")]
    public long Clouds { get; set; }

    [JsonProperty("wind_speed")]
    [JsonPropertyName("wind_speed")]
    public double WindSpeed { get; set; }

    [JsonProperty("wind_deg")]
    [JsonPropertyName("wind_deg")]
    public long WindDeg { get; set; }

    [JsonProperty("weather")]
    [JsonPropertyName("weather")]
    public Weather[] Weather { get; set; }

    [JsonProperty("rain", NullValueHandling = NullValueHandling.Ignore)]
    [JsonPropertyName("rain")]
    public HourlyRain Rain { get; set; }
}

public class HourlyRain
{
    [JsonProperty("1h")]
    [JsonPropertyName("1h")]
    public double The1H { get; set; }
}