// MIT-License
// Copyright BridgingIT GmbH - All Rights Reserved
// Use of this source code is governed by an MIT-style license that can be
// found in the LICENSE file at https://github.com/bridgingit/bitdevkit/license

namespace BridgingIT.DevKit.Common;

using System.Text;

/// <summary>
/// Emits C# source for validated pipeline generation models.
/// </summary>
public static class PipelineSourceEmitter
{
    /// <summary>
    /// Emits the generated source for a validated pipeline model.
    /// </summary>
    /// <param name="model">The validated pipeline generation model.</param>
    /// <returns>The generated C# source.</returns>
    public static string Emit(PipelineGenerationModel model)
    {
        var namespaceName = model.ClassSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : model.ClassSymbol.ContainingNamespace.ToDisplayString();
        var className = model.ClassSymbol.Name;
        var baseType = model.IsGenericPipeline
            ? $"global::BridgingIT.DevKit.Common.PipelineDefinition<{PipelineGeneratorSymbolHelper.ToTypeDisplay(model.ContextType)}>"
            : "global::BridgingIT.DevKit.Common.PipelineDefinition";
        var builderType = model.IsGenericPipeline
            ? $"global::BridgingIT.DevKit.Common.IPipelineDefinitionBuilder<{PipelineGeneratorSymbolHelper.ToTypeDisplay(model.ContextType)}>"
            : "global::BridgingIT.DevKit.Common.IPipelineDefinitionBuilder";

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("// source: PipelineSourceGenerator");

        if (!string.IsNullOrWhiteSpace(namespaceName))
        {
            source.AppendLine($"namespace {namespaceName}");
            source.AppendLine("{");
        }

        source.AppendLine($"partial class {className} : {baseType}");
        source.AppendLine("{");
        source.AppendLine($"    partial void OnConfigureGenerated({builderType} builder);");
        source.AppendLine();
        source.AppendLine($"    protected override void Configure({builderType} builder)");
        source.AppendLine("    {");

        // Registration emission is intentionally ordered to match the authored attribute order
        // and the final validated step order from the generation model.
        foreach (var hook in model.HookRegistrations)
        {
            source.AppendLine($"        builder.AddHook<{PipelineGeneratorSymbolHelper.ToTypeDisplay(hook.TypeSymbol)}>();");
        }

        foreach (var behavior in model.BehaviorRegistrations)
        {
            source.AppendLine($"        builder.AddBehavior<{PipelineGeneratorSymbolHelper.ToTypeDisplay(behavior.TypeSymbol)}>();");
        }

        foreach (var step in model.Steps)
        {
            source.AppendLine($"        builder.AddStep<{step.GeneratedTypeName}>(\"{PipelineGeneratorSymbolHelper.Escape(step.StepName)}\");");
        }

        source.AppendLine("        OnConfigureGenerated(builder);");
        source.AppendLine("    }");
        source.AppendLine();

        foreach (var step in model.Steps)
        {
            EmitStep(source, model, step);
            source.AppendLine();
        }

        source.AppendLine("}");

        if (!string.IsNullOrWhiteSpace(namespaceName))
        {
            source.AppendLine("}");
        }

        return source.ToString();
    }

    private static void EmitStep(StringBuilder source, PipelineGenerationModel model, PipelineStepGenerationModel step)
    {
        var baseType = step.IsAsync
            ? model.IsGenericPipeline
                ? $"global::BridgingIT.DevKit.Common.AsyncPipelineStep<{PipelineGeneratorSymbolHelper.ToTypeDisplay(model.ContextType)}>"
                : "global::BridgingIT.DevKit.Common.AsyncPipelineStep"
            : model.IsGenericPipeline
                ? $"global::BridgingIT.DevKit.Common.PipelineStep<{PipelineGeneratorSymbolHelper.ToTypeDisplay(model.ContextType)}>"
                : "global::BridgingIT.DevKit.Common.PipelineStep";

        source.AppendLine($"    public class {step.GeneratedTypeName} : {baseType}");
        source.AppendLine("    {");

        if (!step.IsStatic)
        {
            source.AppendLine($"        private readonly {PipelineGeneratorSymbolHelper.ToTypeDisplay(model.ClassSymbol)} owner;");
        }

        foreach (var parameter in step.Parameters.Where(static parameter => parameter.Kind == PipelineStepParameterKind.Service))
        {
            source.AppendLine($"        private readonly {PipelineGeneratorSymbolHelper.ToTypeDisplay(parameter.Symbol.Type)} {PipelineGeneratorSymbolHelper.GetFieldName(parameter.Symbol.Name)};");
        }

        var ctorParameters = new List<string>();
        if (!step.IsStatic)
        {
            ctorParameters.Add($"{PipelineGeneratorSymbolHelper.ToTypeDisplay(model.ClassSymbol)} owner");
        }

        ctorParameters.AddRange(step.Parameters
            .Where(static parameter => parameter.Kind == PipelineStepParameterKind.Service)
            .Select(parameter => $"{PipelineGeneratorSymbolHelper.ToTypeDisplay(parameter.Symbol.Type)} {parameter.Symbol.Name}"));

        source.AppendLine($"        public {step.GeneratedTypeName}({string.Join(", ", ctorParameters)})");
        source.AppendLine("        {");
        if (!step.IsStatic)
        {
            source.AppendLine("            this.owner = owner;");
        }

        foreach (var parameter in step.Parameters.Where(static parameter => parameter.Kind == PipelineStepParameterKind.Service))
        {
            source.AppendLine($"            this.{PipelineGeneratorSymbolHelper.GetFieldName(parameter.Symbol.Name)} = {parameter.Symbol.Name};");
        }

        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine($"        public override string Name => \"{PipelineGeneratorSymbolHelper.Escape(step.StepName)}\";");
        source.AppendLine();

        if (step.IsAsync)
        {
            if (model.IsGenericPipeline)
            {
                source.AppendLine($"        protected override async global::System.Threading.Tasks.ValueTask<global::BridgingIT.DevKit.Common.PipelineControl> ExecuteAsync({PipelineGeneratorSymbolHelper.ToTypeDisplay(model.ContextType)} context, global::BridgingIT.DevKit.Common.Result result, global::BridgingIT.DevKit.Common.PipelineExecutionOptions options, global::System.Threading.CancellationToken cancellationToken)");
            }
            else
            {
                source.AppendLine("        protected override async global::System.Threading.Tasks.ValueTask<global::BridgingIT.DevKit.Common.PipelineControl> ExecuteAsync(global::BridgingIT.DevKit.Common.Result result, global::BridgingIT.DevKit.Common.PipelineExecutionOptions options, global::System.Threading.CancellationToken cancellationToken)");
            }
        }
        else if (model.IsGenericPipeline)
        {
            source.AppendLine($"        protected override global::BridgingIT.DevKit.Common.PipelineControl Execute({PipelineGeneratorSymbolHelper.ToTypeDisplay(model.ContextType)} context, global::BridgingIT.DevKit.Common.Result result, global::BridgingIT.DevKit.Common.PipelineExecutionOptions options)");
        }
        else
        {
            source.AppendLine("        protected override global::BridgingIT.DevKit.Common.PipelineControl Execute(global::BridgingIT.DevKit.Common.Result result, global::BridgingIT.DevKit.Common.PipelineExecutionOptions options)");
        }

        source.AppendLine("        {");
        EmitInvocation(source, model, step);
        source.AppendLine("        }");
        source.AppendLine("    }");
    }

    private static void EmitInvocation(StringBuilder source, PipelineGenerationModel model, PipelineStepGenerationModel step)
    {
        var invocationTarget = step.IsStatic
            ? PipelineGeneratorSymbolHelper.ToTypeDisplay(model.ClassSymbol)
            : "this.owner";

        var args = step.Parameters.Select(parameter => parameter.Kind switch
        {
            PipelineStepParameterKind.Context => "context",
            PipelineStepParameterKind.Result => "result",
            PipelineStepParameterKind.CancellationToken => "cancellationToken",
            _ => $"this.{PipelineGeneratorSymbolHelper.GetFieldName(parameter.Symbol.Name)}",
        });

        var invocation = $"{invocationTarget}.{step.MethodSymbol.Name}({string.Join(", ", args)})";

        // Generated wrappers normalize the author-friendly method shapes back to PipelineControl
        // so every step behaves uniformly once it enters the runtime pipeline engine.
        switch (step.ReturnKind)
        {
            case PipelineStepReturnKind.Void:
                source.AppendLine($"            {invocation};");
                source.AppendLine("            return global::BridgingIT.DevKit.Common.PipelineControl.Continue(result);");
                break;
            case PipelineStepReturnKind.Task:
                source.AppendLine($"            await {invocation};");
                source.AppendLine("            return global::BridgingIT.DevKit.Common.PipelineControl.Continue(result);");
                break;
            case PipelineStepReturnKind.Result:
                source.AppendLine($"            var nextResult = {invocation};");
                source.AppendLine("            return global::BridgingIT.DevKit.Common.PipelineControl.Continue(nextResult);");
                break;
            case PipelineStepReturnKind.TaskOfResult:
                source.AppendLine($"            var nextResult = await {invocation};");
                source.AppendLine("            return global::BridgingIT.DevKit.Common.PipelineControl.Continue(nextResult);");
                break;
            case PipelineStepReturnKind.PipelineControl:
                source.AppendLine($"            return {invocation};");
                break;
            case PipelineStepReturnKind.TaskOfPipelineControl:
                source.AppendLine($"            return await {invocation};");
                break;
        }
    }
}
