// <auto-generated/>
#pragma warning disable CS0618
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.Authorize;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.Debuginfo;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.Logout;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.Token;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.Userinfo;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.WellKnown;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect
{
    /// <summary>
    /// Builds and executes requests for operations under \api\_system\identity\connect
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConnectRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The authorize property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.Authorize.AuthorizeRequestBuilder Authorize
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.Authorize.AuthorizeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The debuginfo property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.Debuginfo.DebuginfoRequestBuilder Debuginfo
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.Debuginfo.DebuginfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logout property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.Logout.LogoutRequestBuilder Logout
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.Logout.LogoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The token property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.Token.TokenRequestBuilder Token
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.Token.TokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userinfo property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.Userinfo.UserinfoRequestBuilder Userinfo
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.Userinfo.UserinfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The wellKnown property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.WellKnown.WellKnownRequestBuilder WellKnown
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.WellKnown.WellKnownRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.ConnectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConnectRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/_system/identity/connect", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Identity.Connect.ConnectRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConnectRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/_system/identity/connect", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
