<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>BridgingIT.DevKit.Presentation.UnitTests.ModulesFixtures</AssemblyName>
    <RootNamespace>BridgingIT.DevKit.Presentation.UnitTests.ModulesFixtures</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Common.Modules\Common.Modules.csproj" />
  </ItemGroup>

</Project>
