// <auto-generated/>
#pragma warning disable CS0618
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Messaging.Messages;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Messaging
{
    /// <summary>
    /// Builds and executes requests for operations under \api\_system\messaging
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MessagingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The messages property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Messaging.Messages.MessagesRequestBuilder Messages
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Messaging.Messages.MessagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Messaging.MessagingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MessagingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/_system/messaging", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Messaging.MessagingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MessagingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/_system/messaging", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
