// <auto-generated/>
#pragma warning disable CS0618
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Subscriptions.History.Item.ChangeSets.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Subscriptions.History.Item.ChangeSets
{
    /// <summary>
    /// Builds and executes requests for operations under \api\core\subscriptions\history\{entityId}\change-sets
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChangeSetsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.api.core.subscriptions.history.item.changeSets.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Subscriptions.History.Item.ChangeSets.Item.WithChangeSetItemRequestBuilder"/></returns>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Subscriptions.History.Item.ChangeSets.Item.WithChangeSetItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("changeSetId", position);
                return new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Subscriptions.History.Item.ChangeSets.Item.WithChangeSetItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.api.core.subscriptions.history.item.changeSets.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Subscriptions.History.Item.ChangeSets.Item.WithChangeSetItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Subscriptions.History.Item.ChangeSets.Item.WithChangeSetItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("changeSetId", position);
                return new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Subscriptions.History.Item.ChangeSets.Item.WithChangeSetItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Subscriptions.History.Item.ChangeSets.ChangeSetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChangeSetsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/core/subscriptions/history/{entityId}/change-sets", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Subscriptions.History.Item.ChangeSets.ChangeSetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChangeSetsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/core/subscriptions/history/{entityId}/change-sets", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
