// <auto-generated/>
#pragma warning disable CS0618
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.Directories;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.Events;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.Files;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.Health;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.Provider;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\_system\{providerName}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProviderNameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The directories property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.Directories.DirectoriesRequestBuilder Directories
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.Directories.DirectoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The events property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.Events.EventsRequestBuilder Events
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The files property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.Files.FilesRequestBuilder Files
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The health property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.Health.HealthRequestBuilder Health
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.Health.HealthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The provider property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.Provider.ProviderRequestBuilder Provider
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.Provider.ProviderRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.WithProviderNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProviderNameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/_system/{providerName}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.WithProviderNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProviderNameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/_system/{providerName}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
