// <auto-generated/>
#pragma warning disable CS0618
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Item;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Jobs;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Locations;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Logentries;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Messaging;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Metrics;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Notifications;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Orchestrations;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Queueing;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.System;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \_bdk\api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The jobs property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Jobs.JobsRequestBuilder Jobs
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Jobs.JobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The locations property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Locations.LocationsRequestBuilder Locations
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Locations.LocationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logentries property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Logentries.LogentriesRequestBuilder Logentries
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Logentries.LogentriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The messaging property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Messaging.MessagingRequestBuilder Messaging
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Messaging.MessagingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metrics property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Metrics.MetricsRequestBuilder Metrics
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Metrics.MetricsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notifications property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Notifications.NotificationsRequestBuilder Notifications
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Notifications.NotificationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orchestrations property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Orchestrations.OrchestrationsRequestBuilder Orchestrations
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Orchestrations.OrchestrationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The queueing property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Queueing.QueueingRequestBuilder Queueing
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Queueing.QueueingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The system property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.System.SystemRequestBuilder System
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.System.SystemRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.bdk.api.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Item.WithProviderNameItemRequestBuilder"/></returns>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Item.WithProviderNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("providerName", position);
                return new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.Item.WithProviderNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/_bdk/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Bdk.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/_bdk/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
