@baseUrl = https://localhost:5001

###################################################################################
### API [GET] GetSystem                                                                #
GET {{baseUrl}}/_bdk/api HTTP/1.1

Content-Type: application/json

###################################################################################
### API [GET] GetEcho                                                                #
GET {{baseUrl}}/_bdk/api/echo HTTP/1.1

Content-Type: application/json

###################################################################################
### API [GET] GetInfo                                                                #
GET {{baseUrl}}/_bdk/api/info HTTP/1.1

Content-Type: application/json

###################################################################################
### API [GET] GetModules                                                                #
GET {{baseUrl}}/_bdk/api/modules HTTP/1.1

Content-Type: application/json