// <auto-generated/>
#pragma warning disable CS0618
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Todoitems.Dataporter.Export;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Todoitems.Dataporter.Import;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Todoitems.Dataporter.Validate;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Todoitems.Dataporter
{
    /// <summary>
    /// Builds and executes requests for operations under \api\core\todoitems\dataporter
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DataporterRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The export property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Todoitems.Dataporter.Export.ExportRequestBuilder Export
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Todoitems.Dataporter.Export.ExportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The import property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Todoitems.Dataporter.Import.ImportRequestBuilder Import
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Todoitems.Dataporter.Import.ImportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The validate property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Todoitems.Dataporter.Validate.ValidateRequestBuilder Validate
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Todoitems.Dataporter.Validate.ValidateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Todoitems.Dataporter.DataporterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DataporterRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/core/todoitems/dataporter", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api.Core.Todoitems.Dataporter.DataporterRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DataporterRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/core/todoitems/dataporter", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
