// MIT-License
// Copyright BridgingIT GmbH - All Rights Reserved
// Use of this source code is governed by an MIT-style license that can be
// found in the LICENSE file at https://github.com/bridgingit/bitdevkit/license

namespace BridgingIT.DevKit.Infrastructure.EntityFramework;

using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Migrations.Operations;
using Microsoft.EntityFrameworkCore.Update;
using System;
using System.Linq;

/// <summary>
///     A custom SQL Server <see cref="MigrationsSqlGenerator"/> that emits
///     idempotent DDL statements.
///
///     This generator wraps <c>CREATE</c> and <c>DROP</c> statements for tables,
///     indexes, sequences, and constraints in <c>IF EXISTS</c> / <c>IF NOT EXISTS</c>
///     guards, preventing errors when schema objects already exist or have been removed.
///
///     It allows repeated or parallel migration executions to remain resilient.
/// </summary>
/// <remarks>
///     Register this generator via:
///     <code>
///     options.UseSqlServer(connectionString)
///            .ReplaceService&lt;IMigrationsSqlGenerator, IdempotentSqlServerMigrationsSqlGenerator&gt;();
///     </code>
/// </remarks>
public class SqlServerIdempotentMigrationsSqlGenerator(
    MigrationsSqlGeneratorDependencies dependencies,
    ICommandBatchPreparer commandBatchPreparer)
    : SqlServerMigrationsSqlGenerator(dependencies, commandBatchPreparer)
{
    /// <summary>
    ///     Captures the SQL text generated by the given action using a temporary
    ///     builder that shares this generator’s dependencies.
    /// </summary>
    private string CaptureInnerSql(Action<MigrationCommandListBuilder> action)
    {
        var innerBuilder = new MigrationCommandListBuilder(this.Dependencies);
        action(innerBuilder);
        return string.Join(Environment.NewLine,
            innerBuilder.GetCommandList().Select(c => c.CommandText));
    }

    // ---------- TABLES ----------

    /// <inheritdoc />
    protected override void Generate(
        CreateTableOperation operation,
        IModel model,
        MigrationCommandListBuilder builder,
    bool terminate = true)
    {
        var schema = operation.Schema ?? "dbo";
        var table = operation.Name;

        builder
            .AppendLine("-- Create Table")
            .AppendLine("IF NOT EXISTS (")
            .AppendLine("    SELECT 1 FROM sys.tables t")
            .AppendLine("    JOIN sys.schemas s ON s.schema_id = t.schema_id")
            .AppendLine($"    WHERE t.name = N'{table}' AND s.name = N'{schema}'")
            .AppendLine(")")
            .AppendLine("BEGIN")
            .IncrementIndent();

        base.Generate(operation, model, builder, terminate: false);

        builder
            .DecrementIndent()
            .AppendLine("END;");

        if (terminate)
        {
            builder.AppendLine(this.Dependencies.SqlGenerationHelper.StatementTerminator);
            this.EndStatement(builder);
        }
    }

    /// <inheritdoc />
    protected override void Generate(
        DropTableOperation operation,
        IModel model,
        MigrationCommandListBuilder builder,
        bool terminate = true)
    {
        var schema = operation.Schema ?? "dbo";
        var table = operation.Name;

        builder
            .AppendLine("-- Drop Table")
            .AppendLine("IF EXISTS (")
            .AppendLine("    SELECT 1 FROM sys.tables t")
            .AppendLine("    JOIN sys.schemas s ON s.schema_id = t.schema_id")
            .AppendLine($"    WHERE t.name = N'{table}' AND s.name = N'{schema}'")
            .AppendLine(")")
            .AppendLine("BEGIN")
            .IncrementIndent();

        base.Generate(operation, model, builder, terminate: false);

        builder
            .DecrementIndent()
            .AppendLine("END;");

        if (terminate)
        {
            builder.AppendLine(this.Dependencies.SqlGenerationHelper.StatementTerminator);
            this.EndStatement(builder);
        }
    }

    // ---------- INDEXES ----------

    /// <inheritdoc />
    protected override void Generate(
        CreateIndexOperation operation,
        IModel model,
        MigrationCommandListBuilder builder,
        bool terminate = true)
    {
        var schema = operation.Schema ?? "dbo";
        var table = operation.Table;
        var index = operation.Name;

        builder
               .AppendLine("-- Create Index")
               .AppendLine("IF NOT EXISTS (")
               .AppendLine("    SELECT 1")
               .AppendLine("    FROM sys.indexes i")
               .AppendLine("    JOIN sys.tables t ON t.object_id = i.object_id")
               .AppendLine("    JOIN sys.schemas s ON s.schema_id = t.schema_id")
               .AppendLine($"    WHERE i.name = N'{index}' AND t.name = N'{table}' AND s.name = N'{schema}'")
               .AppendLine(")")
               .AppendLine("BEGIN")
               .IncrementIndent();

        // call base directly; no CaptureInnerSql
        base.Generate(operation, model, builder, terminate: false);

        builder.DecrementIndent()
               .AppendLine("END;");

        if (terminate)
        {
            builder.AppendLine(this.Dependencies.SqlGenerationHelper.StatementTerminator);
            this.EndStatement(builder);
        }
    }

    /// <inheritdoc />
    protected override void Generate(
        DropIndexOperation operation,
        IModel model,
        MigrationCommandListBuilder builder,
        bool terminate = true)
    {
        var schema = operation.Schema ?? "dbo";
        var table = operation.Table;
        var index = operation.Name;

        builder
               .AppendLine("-- Drop Index")
               .AppendLine("IF EXISTS (")
               .AppendLine("    SELECT 1")
               .AppendLine("    FROM sys.indexes i")
               .AppendLine("    JOIN sys.tables t ON t.object_id = i.object_id")
               .AppendLine("    JOIN sys.schemas s ON s.schema_id = t.schema_id")
               .AppendLine($"    WHERE i.name = N'{index}' AND t.name = N'{table}' AND s.name = N'{schema}'")
               .AppendLine(")")
               .AppendLine("BEGIN")
               .IncrementIndent();

        // call base directly; no CaptureInnerSql
        base.Generate(operation, model, builder, terminate: false);

        builder.DecrementIndent()
               .AppendLine("END;");

        if (terminate)
        {
            builder.AppendLine(this.Dependencies.SqlGenerationHelper.StatementTerminator);
            this.EndStatement(builder);
        }
    }

    // ---------- SEQUENCES ----------

    /// <inheritdoc />
    protected override void Generate(CreateSequenceOperation operation, IModel model, MigrationCommandListBuilder builder)
    {
        var schema = operation.Schema ?? "dbo";
        var name = operation.Name;
        var innerSql = this.CaptureInnerSql(i => base.Generate(operation, model, i));

        builder
               .AppendLine("-- Create Sequence")
               .AppendLine("IF NOT EXISTS (")
               .AppendLine("    SELECT 1 FROM sys.sequences seq")
               .AppendLine("    JOIN sys.schemas s ON s.schema_id = seq.schema_id")
               .AppendLine($"    WHERE seq.name = N'{name}' AND s.name = N'{schema}'")
               .AppendLine(")")
               .AppendLine("BEGIN")
               .IncrementIndent()
               .AppendLine(innerSql.TrimEnd())
               .DecrementIndent()
               .AppendLine("END;");

        this.EndStatement(builder);
    }

    /// <inheritdoc />
    protected override void Generate(DropSequenceOperation operation, IModel model, MigrationCommandListBuilder builder)
    {
        var schema = operation.Schema ?? "dbo";
        var name = operation.Name;
        var innerSql = this.CaptureInnerSql(i => base.Generate(operation, model, i));

        builder
               .AppendLine("-- Drop Sequence")
               .AppendLine("IF EXISTS (")
               .AppendLine("    SELECT 1 FROM sys.sequences seq")
               .AppendLine("    JOIN sys.schemas s ON s.schema_id = seq.schema_id")
               .AppendLine($"    WHERE seq.name = N'{name}' AND s.name = N'{schema}'")
               .AppendLine(")")
               .AppendLine("BEGIN")
               .IncrementIndent()
               .AppendLine(innerSql.TrimEnd())
               .DecrementIndent()
               .AppendLine("END;");

        this.EndStatement(builder);
    }

    // ---------- CONSTRAINTS ----------

    /// <inheritdoc />
    protected override void Generate(AddPrimaryKeyOperation operation, IModel model, MigrationCommandListBuilder builder, bool terminate = true)
    {
        var schema = operation.Schema ?? "dbo";
        var name = operation.Name;
        var innerSql = this.CaptureInnerSql(i => base.Generate(operation, model, i, terminate: false));

        builder
               .AppendLine("-- Add PrimaryKey")
               .AppendLine("IF NOT EXISTS (")
               .AppendLine("    SELECT 1 FROM sys.key_constraints kc")
               .AppendLine("    JOIN sys.schemas s ON s.schema_id = kc.schema_id")
               .AppendLine($"    WHERE kc.name = N'{name}' AND s.name = N'{schema}'")
               .AppendLine(")")
               .AppendLine("BEGIN")
               .IncrementIndent()
               .AppendLine(innerSql.TrimEnd())
               .DecrementIndent()
               .AppendLine("END;");

        this.EndStatement(builder);
    }

    /// <inheritdoc />
    protected override void Generate(DropPrimaryKeyOperation operation, IModel model, MigrationCommandListBuilder builder, bool terminate = true)
    {
        var schema = operation.Schema ?? "dbo";
        var name = operation.Name;
        var innerSql = this.CaptureInnerSql(i => base.Generate(operation, model, i, terminate: false));

        builder
               .AppendLine("-- Drop PrimaryKey")
               .AppendLine("IF EXISTS (")
               .AppendLine("    SELECT 1 FROM sys.key_constraints kc")
               .AppendLine("    JOIN sys.schemas s ON s.schema_id = kc.schema_id")
               .AppendLine($"    WHERE kc.name = N'{name}' AND s.name = N'{schema}'")
               .AppendLine(")")
               .AppendLine("BEGIN")
               .IncrementIndent()
               .AppendLine(innerSql.TrimEnd())
               .DecrementIndent()
               .AppendLine("END;");

        this.EndStatement(builder);
    }

    /// <inheritdoc />
    protected override void Generate(AddForeignKeyOperation operation, IModel model, MigrationCommandListBuilder builder, bool terminate = true)
    {
        var schema = operation.Schema ?? "dbo";
        var table = operation.Table;
        var name = operation.Name;
        var innerSql = this.CaptureInnerSql(i => base.Generate(operation, model, i, terminate: false));

        builder
               .AppendLine("-- Add ForeignKey")
               .AppendLine("IF NOT EXISTS (")
               .AppendLine("    SELECT 1 FROM sys.foreign_keys fk")
               .AppendLine("    JOIN sys.tables t ON t.object_id = fk.parent_object_id")
               .AppendLine("    JOIN sys.schemas s ON s.schema_id = t.schema_id")
               .AppendLine($"    WHERE fk.name = N'{name}' AND t.name = N'{table}' AND s.name = N'{schema}'")
               .AppendLine(")")
               .AppendLine("BEGIN")
               .IncrementIndent()
               .AppendLine(innerSql.TrimEnd())
               .DecrementIndent()
               .AppendLine("END;");

        this.EndStatement(builder);
    }

    /// <inheritdoc />
    protected override void Generate(DropForeignKeyOperation operation, IModel model, MigrationCommandListBuilder builder, bool terminate = true)
    {
        var schema = operation.Schema ?? "dbo";
        var table = operation.Table;
        var name = operation.Name;
        var innerSql = this.CaptureInnerSql(i => base.Generate(operation, model, i, terminate: false));

        builder
               .AppendLine("-- Drop ForeignKey")
               .AppendLine("IF EXISTS (")
               .AppendLine("    SELECT 1 FROM sys.foreign_keys fk")
               .AppendLine("    JOIN sys.tables t ON t.object_id = fk.parent_object_id")
               .AppendLine("    JOIN sys.schemas s ON s.schema_id = t.schema_id")
               .AppendLine($"    WHERE fk.name = N'{name}' AND t.name = N'{table}' AND s.name = N'{schema}'")
               .AppendLine(")")
               .AppendLine("BEGIN")
               .IncrementIndent()
               .AppendLine(innerSql.TrimEnd())
               .DecrementIndent()
               .AppendLine("END;");

        this.EndStatement(builder);
    }

    /// <inheritdoc />
    protected override void Generate(AddCheckConstraintOperation operation, IModel model, MigrationCommandListBuilder builder)
    {
        var schema = operation.Schema ?? "dbo";
        var table = operation.Table;
        var name = operation.Name;
        var innerSql = this.CaptureInnerSql(i => base.Generate(operation, model, i));

        builder
               .AppendLine("-- Add CheckConstraint")
               .AppendLine("IF NOT EXISTS (")
               .AppendLine("    SELECT 1 FROM sys.check_constraints cc")
               .AppendLine("    JOIN sys.tables t ON t.object_id = cc.parent_object_id")
               .AppendLine("    JOIN sys.schemas s ON s.schema_id = t.schema_id")
               .AppendLine($"    WHERE cc.name = N'{name}' AND t.name = N'{table}' AND s.name = N'{schema}'")
               .AppendLine(")")
               .AppendLine("BEGIN")
               .IncrementIndent()
               .AppendLine(innerSql.TrimEnd())
               .DecrementIndent()
               .AppendLine("END;");

        this.EndStatement(builder);
    }

    /// <inheritdoc />
    protected override void Generate(DropCheckConstraintOperation operation, IModel model, MigrationCommandListBuilder builder)
    {
        var schema = operation.Schema ?? "dbo";
        var table = operation.Table;
        var name = operation.Name;
        var innerSql = this.CaptureInnerSql(i => base.Generate(operation, model, i));

        builder
               .AppendLine("-- Drop CheckConstraint")
               .AppendLine("IF EXISTS (")
               .AppendLine("    SELECT 1 FROM sys.check_constraints cc")
               .AppendLine("    JOIN sys.tables t ON t.object_id = cc.parent_object_id")
               .AppendLine("    JOIN sys.schemas s ON s.schema_id = t.schema_id")
               .AppendLine($"    WHERE cc.name = N'{name}' AND t.name = N'{table}' AND s.name = N'{schema}'")
               .AppendLine(")")
               .AppendLine("BEGIN")
               .IncrementIndent()
               .AppendLine(innerSql.TrimEnd())
               .DecrementIndent()
               .AppendLine("END;");

        this.EndStatement(builder);
    }

    /// <inheritdoc />
    protected override void Generate(AddUniqueConstraintOperation operation, IModel model, MigrationCommandListBuilder builder)
    {
        var schema = operation.Schema ?? "dbo";
        var table = operation.Table;
        var name = operation.Name;
        var innerSql = this.CaptureInnerSql(i => base.Generate(operation, model, i));

        builder
               .AppendLine("-- Add UniqueConstraint")
               .AppendLine("IF NOT EXISTS (")
               .AppendLine("    SELECT 1 FROM sys.key_constraints kc")
               .AppendLine("    JOIN sys.tables t ON t.object_id = kc.parent_object_id")
               .AppendLine("    JOIN sys.schemas s ON s.schema_id = t.schema_id")
               .AppendLine($"    WHERE kc.type = 'UQ' AND kc.name = N'{name}' AND t.name = N'{table}' AND s.name = N'{schema}'")
               .AppendLine(")")
               .AppendLine("BEGIN")
               .IncrementIndent()
               .AppendLine(innerSql.TrimEnd())
               .DecrementIndent()
               .AppendLine("END;");

        this.EndStatement(builder);
    }

    /// <inheritdoc />
    protected override void Generate(DropUniqueConstraintOperation operation, IModel model, MigrationCommandListBuilder builder)
    {
        var schema = operation.Schema ?? "dbo";
        var table = operation.Table;
        var name = operation.Name;
        var innerSql = this.CaptureInnerSql(i => base.Generate(operation, model, i));

        builder
               .AppendLine("-- Drop UniqueConstraint")
               .AppendLine("IF EXISTS (")
               .AppendLine("    SELECT 1 FROM sys.key_constraints kc")
               .AppendLine("    JOIN sys.tables t ON t.object_id = kc.parent_object_id")
               .AppendLine("    JOIN sys.schemas s ON s.schema_id = t.schema_id")
               .AppendLine($"    WHERE kc.type = 'UQ' AND kc.name = N'{name}' AND t.name = N'{table}' AND s.name = N'{schema}'")
               .AppendLine(")")
               .AppendLine("BEGIN")
               .IncrementIndent()
               .AppendLine(innerSql.TrimEnd())
               .DecrementIndent()
               .AppendLine("END;");

        this.EndStatement(builder);
    }

    // ---------- SCHEMA ----------

    /// <inheritdoc />
    protected override void Generate(EnsureSchemaOperation operation, IModel model, MigrationCommandListBuilder builder)
    {
        if (string.Equals(operation.Name, "dbo", StringComparison.OrdinalIgnoreCase))
            return;

        builder.AppendLine("IF SCHEMA_ID(N'" + operation.Name + "') IS NULL")
               .AppendLine("    EXEC('CREATE SCHEMA [" + operation.Name + "]');")
               .EndCommand();
    }
}