// <auto-generated/>
#pragma warning disable CS0618
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Echo;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Info;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Jobs;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Locations;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Messaging;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Modules;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Notifications;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Queueing;
using BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system
{
    /// <summary>
    /// Builds and executes requests for operations under \api\_system
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class _systemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The echo property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Echo.EchoRequestBuilder Echo
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Echo.EchoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The info property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Info.InfoRequestBuilder Info
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Info.InfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The jobs property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Jobs.JobsRequestBuilder Jobs
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Jobs.JobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The locations property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Locations.LocationsRequestBuilder Locations
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Locations.LocationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The messaging property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Messaging.MessagingRequestBuilder Messaging
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Messaging.MessagingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The modules property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Modules.ModulesRequestBuilder Modules
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Modules.ModulesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notifications property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Notifications.NotificationsRequestBuilder Notifications
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Notifications.NotificationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The queueing property</summary>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Queueing.QueueingRequestBuilder Queueing
        {
            get => new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Queueing.QueueingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.api._system.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.WithProviderNameItemRequestBuilder"/></returns>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.WithProviderNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("providerName", position);
                return new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system.Item.WithProviderNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system._systemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public _systemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/_system", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system._systemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public _systemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/_system", rawUrl)
        {
        }
        /// <summary>
        /// _System.Get
        /// </summary>
        /// <returns>A <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system._systemGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system._systemGetResponse?> GetAs_systemGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system._systemGetResponse> GetAs_systemGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "500", global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system._systemGetResponse>(requestInfo, global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system._systemGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// _System.Get
        /// </summary>
        /// <returns>A <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system._systemResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.ProblemDetails">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAs_systemGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system._systemResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system._systemResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "500", global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system._systemResponse>(requestInfo, global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system._systemResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// _System.Get
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system._systemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system._systemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::BridgingIT.DevKit.Examples.DoFiesta.Presentation.Gen.Api._system._systemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class _systemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
